// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsxlvinbnpxculazowih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzeGx2aW5ibnB4Y3VsYXpvd2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTU0ODEsImV4cCI6MjA3MTYzMTQ4MX0.Z2vNR6_s5_nSA2YIeoMIRV1mp2eBd6nZid4--W1dX3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});